version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  consumer-core:
    image: farmstack/trusted-connector
    tty: true
    stdin_open: true
    volumes:
      - ./logs/provider/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../../fs-assets/deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../../../fs-assets/etc/settings.mapdb:/root/etc/settings.mapdb
      - ../../../fs-assets/sample-certificates/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ../../../fs-assets/sample-certificates/truststore.p12:/root/etc/truststore.p12
      - ./farmstack-farmos-consumer.xml:/root/deploy/farmstack-farmos-consumer.xml
      
    # Uncomment to run the provider & consumer nodes on separate server
    # replace x.x.x.x with the consumer ip address
#    extra_hosts:
#      - "provider-core:13.59.74.187"

    ports:
      - 29292:29292
      # - "8181:8181"
      # - "5005:5005"
      # - "8443:8443"
      - 9001:9001

    # Using two networks ids-wide and provider-internal for external comunication and internal communication respectively
    networks:
      - ids-wide
      - farmos-consumer-internal

  farmos-consumer:
    image: farmstack/farmos-consumer:restapi
    ports:
      - 5003:5003
    networks:
      - farmos-consumer-internal

networks:
  ids-wide:
    driver: bridge
  farmos-consumer-internal:
    driver: bridge