version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm
    networks:
      - farmos-external

  www:
    depends_on:
      - db
    image: farmos/farmos:2.x-dev
    volumes:
      - './php.ini:/usr/local/etc/php/conf.d/farmos.ini'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    networks:
      - farmos-external

networks:
  farmos-external:
    driver: bridge