# Generated by Django 2.2 on 2021-10-04 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid

def insert_models(apps, schema_editor):
    AVAILABLE_APPS = [
        {
            'name': 'gsheets',
            'display_name': 'Google Sheets',
            'port': '3001',
            'icon': 'google-sheets.png',
        },
        {
            'name': 'display',
            'display_name': 'Display Table',
            'port': '8081',
            'icon': 'table.png',
        },
        {
            'name': 'csv',
            'display_name': 'Download CSV',
            'port': '3001',
            'icon': 'table.png',
        }
    ]
    ConnectorApp = apps.get_model('connector_api','ConnectorApp')
    for app in AVAILABLE_APPS:
        connector_app = ConnectorApp(**app)
        connector_app.save()

def remove_models(app, schema_editor):
    ConnectorApp = apps.get_model('connector_api','ConnectorApp')
    ConnectorApp.objects.all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorApp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('icon', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=10)),
                ('connector_type', models.CharField(blank=True, max_length=60, null=True)),
                ('paired_connector', models.CharField(blank=True, max_length=60, null=True)),
                ('connector_app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connector_api.ConnectorApp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(insert_models, remove_models),
    ]
